# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20170829_0648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Box',
            new_name='Item',
        ),
    ]
