# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20170829_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[('1', 'Draft'), ('2', 'For Vetting'), ('3', 'Published')], default=1),
        ),
    ]
