# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20170829_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_category', to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_id_for_category', to='recipes.Recipe'),
        ),
    ]
