# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20170830_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Recipe_Category',
        ),
    ]
