# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20170830_1039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe_Category',
            new_name='Category',
        ),
    ]
