# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20170831_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_category',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_categories', to='recipes.Recipe'),
        ),
    ]
