# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20170831_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='step',
            name='video_link',
            field=models.URLField(blank=True),
        ),
    ]
