# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='follows',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='views',
            name='slug',
        ),
    ]
