# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20170829_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featured',
            old_name='parent_cookbook',
            new_name='cookbook',
        ),
        migrations.RenameField(
            model_name='featured',
            old_name='parent_recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='featured',
            old_name='parent_user',
            new_name='user',
        ),
    ]
