# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0015_auto_20170913_0513'),
        ('subscriptions', '0003_auto_20170914_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('feature_type', models.CharField(choices=[('RE', 'Recipe'), ('CB', 'Cookbook'), ('US', 'User')], max_length=2)),
                ('recipe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
            options={
                'ordering': ('id', 'created_date'),
            },
        ),
        migrations.CreateModel(
            name='FeaturedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('feature_type', models.CharField(choices=[('RE', 'Recipe'), ('CB', 'Cookbook'), ('US', 'User')], max_length=2)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id', 'created_date'),
            },
        ),
        migrations.RemoveField(
            model_name='featured',
            name='cookbook',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='featured',
            name='user',
        ),
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
