# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170913_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Singapore', max_length=50),
        ),
    ]
