# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20170829_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories_defined',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defined_category', to='categories.Category'),
        ),
    ]
