# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20170831_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories_defined',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
