# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20170831_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories_defined',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defined_category_values', to='categories.Category'),
        ),
    ]
